Add and Removed
ClarenceAtim/ToDoList pull request #3
Opened 2023-06-16 11:34 UTC by ClarenceAtim

#Features#

Remove all hardcoded items from the tasks array.
Created a new JavaScript file for the new functionality.
Implemented a function for adding a new task (
Implemented a function for deleting a task (remove an element from the array).
Implemented a function for editing task descriptions.

2023-06-16 14:59 UTC, ClarenceAtim commented
NOT able to see comments

2023-06-16 16:20 UTC, AdnanOlarmmi requested changes
Hi @ClarenceAtim, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Add and remove functionalities working appropriately.
- App follows wireframe design.

## Required Changes ♻️
- [ ] Kindly note that for this project, you hardly committed, 🙂 Committing frequently gives you the advantage of troubleshooting commits that have broken something in the build process and being able to revert back without losing too much work. You also get the added advantage of seeing changes easier without wading through a file with 1000 line additions. Check this [link](https://ilikekillnerds.com/2014/11/commit-often-merge-often-push-often-and-relax/#:~:text=Committing%20frequently%20gives%20you%20the,file%20with%201000%20line%20additions.) for a short interesting article about git commits, merges and pushes. it's sweet I tell you 😀.


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 16:20 UTC, AdnanOlarmmi commented on src/index.js
> +
- [ ] According to the requirement, adding or removing an item from the array should update the indexes of the array,

This happened when I deleted the last element and added a new one instead, the new item has one of the old item's indexes which in turn fires invent on both if one is clicked, when I tried to delete one, both got deleted because the events are fired by Id

<img width="549" alt="image" src="https://github.com/ClarenceAtim/ToDoList/assets/41163571/c6581f6b-ec6b-48bb-8d54-79b6d1e42626">

2023-06-17 10:29 UTC, VICTOR-CHUKWU requested changes
Hi @ClarenceAtim , 
## STATUS: CHANGES REQUIRED :recycle: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 10:29 UTC, VICTOR-CHUKWU commented on src/modules/utility.js
> +};
- [ ] when I edit a task, it does not update the local storage, kindly fix that
![image](https://github.com/ClarenceAtim/ToDoList/assets/66097371/b9b9b4af-3f2e-485a-8fdd-35f14ec820f1)

2023-06-17 12:22 UTC, ClarenceAtim commented
I have updated the edit function after editing click outside it will  update the local storage

2023-06-17 12:39 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @ClarenceAtim , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Great design
✅ ... Green linters, and fixed bugs

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 12:44 UTC, merged